"""add roles table

Revision ID: 939b47ef27e5
Revises: c47c81d4fda3
Create Date: 2022-05-25 13:33:40.303806

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '939b47ef27e5'
down_revision = 'c47c81d4fda3'
branch_labels = None
depends_on = None


def upgrade():
    roles_table = op.create_table(
        'roles',
        sa.Column('id', sa.Integer, autoincrement=True, primary_key=True),
        sa.Column('name', sa.String(100), nullable=False),
        sa.Column('created', sa.DateTime()),
        sa.Column('modified', sa.DateTime()),
        sa.Column('perm_add', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_modify', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_modify_org', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_publish', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_delegate', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_sync', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_admin', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_audit', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_full', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_auth', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_site_admin', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_regexp_access', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_tagger', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_template', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_sharing_group', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_tag_editor', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_sighting', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_object_template', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_galaxy_editor', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_warninglist', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_publish_zmq', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_publish_kafka', sa.Boolean(), nullable=False, default=False),
        sa.Column('perm_decaying', sa.Boolean(), nullable=False, default=False),
        sa.Column('default_role', sa.Boolean(), nullable=False, default=False),
        sa.Column('restricted_to_site_admin', sa.Boolean(), nullable=False, default=False),
        sa.Column('enforce_rate_limit', sa.Boolean(), nullable=False, default=False),
        sa.Column('rate_limit_count', sa.Integer(), nullable=False, default=0),
        sa.Column('memory_limit', sa.String(255), nullable=False, default=''),
        sa.Column('max_execution_time', sa.String(255), nullable=False, default=''),
    )

    default_roles = [
        {
            'id': 1,
            'name': 'admin',
            'perm_add': True,
            'perm_modify': True,
            'perm_modify_org': True,
            'perm_publish': True,
            'perm_delegate': True,
            'perm_sync': True,
            'perm_admin': True,
            'perm_audit': True,
            'perm_full': True,
            'perm_auth': True,
            'perm_site_admin': True,
            'perm_regexp_access': True,
            'perm_tagger': True,
            'perm_template': True,
            'perm_sharing_group': True,
            'perm_tag_editor': True,
            'perm_sighting': True,
            'perm_object_template': True,
            'perm_galaxy_editor': True,
            'perm_warninglist': True,
            'perm_publish_zmq': True,
            'perm_publish_kafka': True,
            'perm_decaying': True
        },
        {
            'id': 2,
            'name': 'Org Admin',
            'perm_add': True,
            'perm_modify': True,
            'perm_modify_org': True,
            'perm_publish': True,
            'perm_delegate': True,
            'perm_sync': False,
            'perm_admin': True,
            'perm_audit': True,
            'perm_full': False,
            'perm_auth': True,
            'perm_site_admin': False,
            'perm_regexp_access': False,
            'perm_tagger': True,
            'perm_template': True,
            'perm_sharing_group': True,
            'perm_tag_editor': True,
            'perm_sighting': True,
            'perm_object_template': False,
            'perm_galaxy_editor': True,
            'perm_warninglist': False,
            'perm_publish_zmq': True,
            'perm_publish_kafka': True,
            'perm_decaying': True
        },
        {
            'id': 3,
            'name': 'User',
            'perm_add': True,
            'perm_modify': True,
            'perm_modify_org': True,
            'perm_publish': False,
            'perm_delegate': False,
            'perm_sync': False,
            'perm_admin': False,
            'perm_audit': False,
            'perm_full': False,
            'perm_auth': True,
            'perm_site_admin': False,
            'perm_regexp_access': False,
            'perm_tagger': True,
            'perm_template': False,
            'perm_sharing_group': False,
            'perm_tag_editor': False,
            'perm_sighting': True,
            'perm_object_template': False,
            'perm_galaxy_editor': False,
            'perm_warninglist': False,
            'perm_publish_zmq': False,
            'perm_publish_kafka': False,
            'perm_decaying': True,
            'default_role': True
        },
        {
            'id': 4,
            'name': 'Publisher',
            'perm_add': True,
            'perm_modify': True,
            'perm_modify_org': True,
            'perm_publish': True,
            'perm_delegate': True,
            'perm_sync': False,
            'perm_admin': False,
            'perm_audit': False,
            'perm_full': False,
            'perm_auth': True,
            'perm_site_admin': False,
            'perm_regexp_access': False,
            'perm_tagger': True,
            'perm_template': False,
            'perm_sharing_group': False,
            'perm_tag_editor': False,
            'perm_sighting': True,
            'perm_object_template': False,
            'perm_galaxy_editor': False,
            'perm_warninglist': False,
            'perm_publish_zmq': True,
            'perm_publish_kafka': True,
            'perm_decaying': True
        },
        {
            'id': 5,
            'name': 'Sync user',
            'perm_add': True,
            'perm_modify': True,
            'perm_modify_org': True,
            'perm_publish': True,
            'perm_delegate': True,
            'perm_sync': True,
            'perm_admin': False,
            'perm_audit': False,
            'perm_full': False,
            'perm_auth': True,
            'perm_site_admin': False,
            'perm_regexp_access': False,
            'perm_tagger': True,
            'perm_template': False,
            'perm_sharing_group': True,
            'perm_tag_editor': True,
            'perm_sighting': True,
            'perm_object_template': False,
            'perm_galaxy_editor': True,
            'perm_warninglist': False,
            'perm_publish_zmq': True,
            'perm_publish_kafka': True,
            'perm_decaying': True
        },
        {
            'id': 6,
            'name': 'Read Only',
            'perm_add': False,
            'perm_modify': False,
            'perm_modify_org': False,
            'perm_publish': False,
            'perm_delegate': False,
            'perm_sync': False,
            'perm_admin': False,
            'perm_audit': False,
            'perm_full': False,
            'perm_auth': True,
            'perm_site_admin': False,
            'perm_regexp_access': False,
            'perm_tagger': False,
            'perm_template': False,
            'perm_sharing_group': False,
            'perm_tag_editor': False,
            'perm_sighting': False,
            'perm_object_template': False,
            'perm_galaxy_editor': False,
            'perm_warninglist': False,
            'perm_publish_zmq': False,
            'perm_publish_kafka': False,
            'perm_decaying': False
        },
    ]

    op.bulk_insert(roles_table, default_roles)
    op.add_column('users', sa.Column('role_id', sa.Integer(), sa.ForeignKey('roles.id'), nullable=False))


def downgrade():
    op.drop_table('roles')
