export const DISTRIBUTION_LEVEL = {
  ORGANISATION_ONLY: 0,
  COMMUNITY_ONLY: 1,
  CONNECTED_COMMUNITIES: 2,
  ALL_COMMUNITIES: 3,
  SHARING_GROUP: 4,
  INHERIT_EVENT: 5
};

export const THREAT_LEVEL = {
  HIGH: 1,
  MEDIUM: 2,
  LOW: 3,
  UNDEFINED: 4,
};

export const ANALYSIS_LEVEL = {
  INITIAL: 0,
  ONGOING: 1,
  COMPLETE: 2,
};